disabled_rules:
  - line_length
  - force_cast
  - identifier_name
  - vertical_whitespace
  - colon
  - trailing_whitespace
  - opening_brace
  - trailing_newline
  - syntactic_sugar
  - comma
  - control_statement
  - mark
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods