# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VIPER_Architecture' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VIPER_Architecture
  pod 'Alamofire', '~> 4.8.2'
  pod 'AlamofireObjectMapper'
  pod 'ObjectMapper'
  pod 'CryptoSwift'
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftLint'
  pod 'SVProgressHUD'
  
end
