disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- force_cast
- file_length
- identifier_name
- line_length
- function_parameter_count
- multiple_closures_with_trailing_closure
- function_body_length

opt_in_rules:
- empty_count
- empty_string

excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
- /Utilities/NetworkManager.swift
- /Utilities/Utility.swift

function_body_length:
warning: 300
error: 500

function_parameter_count:
warning: 7
error: 9

line_length:
- warning: 150
- error: 200
- ignores_function_declarations: true
- ignores_comments: true
- ignores_urls: true

type_body_length:
warning: 300
error: 500

file_length:
warning: 100
error: 150
ignore_comment_only_lines: true

reporter: "xcode"
