# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVM_Architecture' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  inhibit_all_warnings!

  # Pods for MVVM_Architecture
  pod 'Alamofire', '~> 4.8.2'
  pod 'AlamofireObjectMapper'
  pod 'ObjectMapper'
  pod 'SVProgressHUD'
  pod 'SwiftLint',:inhibit_warnings => true
end
