disabled_rules:
- line_length
- force_cast
- identifier_name
- vertical_whitespace
- colon
- trailing_whitespace
- opening_brace
- trailing_newline
- syntactic_sugar
- comma
- control_statement
- mark
- file_length
- function_body_length
- function_parameter_count
- multiple_closures_with_trailing_closure
- unused_closure_parameter
- cyclomatic_complexity

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - VS_MVP_BaseProj/Components
  - VS_MVP_BaseProj/Constants
